### ISSUE TITLE
install bug

### ISSUE THREAD

**Issue by zhuyuwei999** [ZhenHuangLab/MemXTerminator#4]
MemXTerminator gui &
[1] 1085041
(mxt) [spuser@spgpu MemXTerminator]$ Traceback (most recent call last):
  File "/home/spuser/.conda/envs/mxt/bin/MemXTerminator", line 5, in <module>
    from memxterminator.cli.main_cli import main
  File "/home/spuser/.conda/envs/mxt/lib/python3.9/site-packages/memxterminator/cli/main_cli.py", line 6, in <module>
    from .radonfit_cli import RadonApp, MembraneAnalyzerApp, MembraneSubtractionApp, MicrographMembraneSubtraction_Radon_App
  File "/home/spuser/.conda/envs/mxt/lib/python3.9/site-packages/memxterminator/cli/radonfit_cli.py", line 8, in <module>
    import cupy as cp
  File "/home/spuser/.conda/envs/mxt/lib/python3.9/site-packages/cupy/__init__.py", line 12, in <module>
    _environment._preload_libraries()  # NOQA
  File "/home/spuser/.conda/envs/mxt/lib/python3.9/site-packages/cupy/_environment.py", line 292, in _preload_libraries
    filename = config[lib]['filename']
KeyError: 'filename'

**Comment by ZhenHuangLab** [comment]
Please check the `cupy` library.

You can refer to the installation notes [here](https://zhenhuanglab.github.io/MemXTerminator/tutorials/installation/).
